### ISSUE TITLE
Null Reference running CLI

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#1346]
```
PS C:\Users\zszarka\AppData\Local\ResearchDataManagementPlatform\rdmp-client\cli> ./rdmp ScriptTables "TableInfo:*smi*table*" MySql smi "./creation.sql"
2022-08-08 15:55:06.3768 INFO Dotnet Version:6.0.7 .
2022-08-08 15:55:06.5174 INFO RDMP Version:7.0.17.0 .
2022-08-08 15:55:16.6016 ERROR Object reference not set to an instance of an object. .
2022-08-08 15:55:16.6036 INFO Fatal error occurred so returning -1 . System.NullReferenceException: Object reference not set to an instance of an object.
   at Rdmp.Core.Providers.FavouritesProvider..ctor(IBasicActivateItems activator) in D:\a\RDMP\RDMP\Rdmp.Core\Providers\FavouritesProvider.cs:line 30
   at Rdmp.Core.CommandExecution.BasicActivateItems..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ICheckNotifier globalErrorCheckNotifier) in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\BasicActivateItems.cs:line 146
   at Rdmp.Core.CommandLine.Interactive.ConsoleInputManager..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ICheckNotifier globalErrorCheckNotifier) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\Interactive\ConsoleInputManager.cs:line 51
   at Rdmp.Core.CommandExecution.ThrowImmediatelyActivator..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ICheckNotifier notifier) in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\ThrowImmediatelyActivator.cs:line 19
   at Rdmp.Core.CommandLine.RdmpCommandLineBootStrapper.Run(RDMPCommandLineOptions opts, IRunner explicitRunner, IRDMPPlatformRepositoryServiceLocator existingLocator) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\RdmpCommandLineBootStrapper.cs:line 137
   at Rdmp.Core.CommandLine.RdmpCommandLineBootStrapper.RunCmd(ExecuteCommandOptions opts, IRDMPPlatformRepositoryServiceLocator existingLocator) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\RdmpCommandLineBootStrapper.cs:line 103
   at Rdmp.Core.Program.<>c.<HandleArguments>b__1_10(ExecuteCommandOptions opts) in D:\a\RDMP\RDMP\Tools\rdmp\Program.cs:line 101
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 parsedFunc9, Func`2 parsedFunc10, Func`2 parsedFunc11, Func`2 notParsedFunc)
   at Rdmp.Core.Program.HandleArguments(String[] args, Logger logger) in D:\a\RDMP\RDMP\Tools\rdmp\Program.cs:line 76
PS C:\Users\zszarka\AppData\Local\ResearchDataManagementPlatform\rdmp-client\cli> ./rdmp ScriptTables "TableInfo:*smi*table*" MySql smi "./creation.sql"
```

**Comment by tznind** [comment]
This seems to be tied to running the RDMP cli after deleting `Databases.yaml`:

```
PS C:\Users\44777\Downloads\rdmp-cli-win-x64> rm .\Databases.yaml
PS C:\Users\44777\Downloads\rdmp-cli-win-x64> ./rdmp ScriptTables "TableInfo:*smi*table*" MySql smi "./creation.sql"
2022-08-09 08:54:43.5021 INFO Dotnet Version:6.0.7 .
2022-08-09 08:54:43.5199 INFO RDMP Version:7.0.17.0 .
2022-08-09 08:54:43.6389 ERROR Object reference not set to an instance of an object. .
2022-08-09 08:54:43.6389 INFO Fatal error occurred so returning -1 . System.NullReferenceException: Object reference not set to an instance of an object.
   at Rdmp.Core.Providers.FavouritesProvider..ctor(IBasicActivateItems activator) in D:\a\RDMP\RDMP\Rdmp.Core\Providers\FavouritesProvider.cs:line 30
   at Rdmp.Core.CommandExecution.BasicActivateItems..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ICheckNotifier globalErrorCheckNotifier) in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\BasicActivateItems.cs:line 146
   at Rdmp.Core.CommandLine.Interactive.ConsoleInputManager..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ICheckNotifier globalErrorCheckNotifier) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\Interactive\ConsoleInputManager.cs:line 51
   at Rdmp.Core.CommandExecution.ThrowImmediatelyActivator..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, ICheckNotifier notifier) in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\ThrowImmediatelyActivator.cs:line 19
   at Rdmp.Core.CommandLine.RdmpCommandLineBootStrapper.Run(RDMPCommandLineOptions opts, IRunner explicitRunner, IRDMPPlatformRepositoryServiceLocator existingLocator) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\RdmpCommandLineBootStrapper.cs:line 137
   at Rdmp.Core.CommandLine.RdmpCommandLineBootStrapper.RunCmd(ExecuteCommandOptions opts, IRDMPPlatformRepositoryServiceLocator existingLocator) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\RdmpCommandLineBootStrapper.cs:line 103
   at Rdmp.Core.Program.<>c.<HandleArguments>b__1_10(ExecuteCommandOptions opts) in D:\a\RDMP\RDMP\Tools\rdmp\Program.cs:line 101
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 parsedFunc9, Func`2 parsedFunc10, Func`2 parsedFunc11, Func`2 notParsedFunc)
   at Rdmp.Core.Program.HandleArguments(String[] args, Logger logger) in D:\a\RDMP\RDMP\Tools\rdmp\Program.cs:line 76
PS C:\Users\44777\Downloads\rdmp-cli-win-x64> ./rdmp ScriptTables "TableInfo:*smi*table*" MySql smi "./creation.sql"
```
