### ISSUE TITLE
Failed to execute command 'Existing Datasets'

### ISSUE THREAD

**Issue by zzszarka** [HicServices/RDMP#1374]
**Describe the bug**
Failed to execute command 'Existing Datasets' (Type was 'ExecuteCommandAddDatasetsToConfiguration')

The given key '11174' was not present in the dictionary.

**To Reproduce**
1. With the extraction configuration already opened on the right side
2. Left-click the same extraction configuration in the navigation pane (left-side)
3. Add Existing Catalogue
4. Choose the Catalogue
5. See error

**Expected behavior**
The catalogue is added to the configuration without error

**Screenshots**

**RDMP Version**
7.0.17

**Error with Stack Trace**
```
The given key '11174' was not present in the dictionary.
   at Rdmp.Core.Providers.DataExportChildProvider.BuildSelectedDatasets() in D:\a\RDMP\RDMP\Rdmp.Core\Providers\DataExportChildProvider.cs:line 215
   at Rdmp.Core.Providers.DataExportChildProvider.SelectiveRefresh(IExtractionConfiguration ec) in D:\a\RDMP\RDMP\Rdmp.Core\Providers\DataExportChildProvider.cs:line 862
   at Rdmp.Core.Providers.DataExportChildProvider.SelectiveRefresh(IMapsDirectlyToDatabaseTable databaseEntity) in D:\a\RDMP\RDMP\Rdmp.Core\Providers\DataExportChildProvider.cs:line 793
   at ResearchDataManagementPlatform.WindowManagement.ActivateItems.RefreshBus_RefreshObject(Object sender, RefreshObjectEventArgs e) in D:\a\RDMP\RDMP\Application\ResearchDataManagementPlatform\WindowManagement\ActivateItems.cs:line 453
   at Rdmp.UI.Refreshing.RefreshBus.Publish(Object sender, RefreshObjectEventArgs e) in D:\a\RDMP\RDMP\Rdmp.UI\Refreshing\RefreshBus.cs:line 66
   at ResearchDataManagementPlatform.WindowManagement.ActivateItems.Publish(IMapsDirectlyToDatabaseTable databaseEntity) in D:\a\RDMP\RDMP\Application\ResearchDataManagementPlatform\WindowManagement\ActivateItems.cs:line 98
   at Rdmp.Core.CommandExecution.BasicCommandExecution.Publish(IMapsDirectlyToDatabaseTable o) in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\BasicCommandExecution.cs:line 215
   at Rdmp.Core.CommandExecution.AtomicCommands.ExecuteCommandAddDatasetsToConfiguration.Execute() in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\AtomicCommands\ExecuteCommandAddDatasetsToConfiguration.cs:line 102
   at Rdmp.UI.Menus.MenuItems.AtomicCommandMenuItem.OnClick(EventArgs e) in D:\a\RDMP\RDMP\Rdmp.UI\Menus\MenuItems\AtomicCommandMenuItem.cs:line 50
```

**Database Engine**
Sql Server

**Additional context**

**Comment by tznind** [comment]
Was the Catalogue a newly created one?

**Comment by zzszarka** [comment]
No, it existed already

**Comment by tznind** [comment]
Closing this as it is not reproducible and if it occurs again after 8.0.3 there will be more info about the ID / name of the thing that has a collision on.
