### ISSUE TITLE
AutoUpdater bugged

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#1399]
**Describe the bug**

Trying to update from `7.0.17.0` to  `7.0.18.0` is resulting in this error:

```
Method not found: 'Void Microsoft.Web.WebView2.WinForms.WebView2.add_CoreWebView2InitializationCompleted(System.EventHandler`1<Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs>)'.
```

```
   at AutoUpdaterDotNET.UpdateForm.InitializeBrowserControl()
   at AutoUpdaterDotNET.UpdateForm..ctor(UpdateInfoEventArgs args)
   at AutoUpdaterDotNET.AutoUpdater.ShowUpdateForm(UpdateInfoEventArgs args)
   at AutoUpdaterDotNET.AutoUpdater.StartUpdate(Object result)
   at AutoUpdaterDotNET.AutoUpdater.<>c.<Start>b__43_1(Object _, RunWorkerCompletedEventArgs args)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
```

**To Reproduce**
1. Checkout old binary
2. Try to update to latest

**Comment by tznind** [comment]
I've opened an issue in AutoUpdater.NET https://github.com/ravibpatel/AutoUpdater.NET/issues/569 and have found what I think is responsible (mismatching csproj and nuspec file)

**Comment by tznind** [comment]
Issue was resolved in AutoUpdater, users will have to manually update to the latest version of RDMP
