### ISSUE TITLE
[v8.2.0] ImportTableInfo could not find any columns in table

### ISSUE THREAD

**Issue by rkm** [HicServices/RDMP#1874]
**Describe the bug**

Unable to run ImportTableInfo on a postgres database

**To Reproduce**
1. Download RDMP CLI v8.2.0
2. Run the following reproduction

```bash
#!/usr/bin/env bash

set -euxo pipefail

docker kill $(docker ps -q) || true
rm -rf yaml

postgres_id=$(docker run --rm -d -p5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust postgres:15)
sleep 5 # Wait for DB to start

docker exec -i $postgres_id psql -U postgres <<EOF
CREATE DATABASE smi;
\c smi
CREATE SCHEMA dicom;
CREATE TABLE dicom."IO_StudyTable" ("StudyInstanceUID" varchar(255));
INSERT INTO dicom."IO_StudyTable" VALUES ('1.2.3');
CREATE USER rdmp;
CREATE DATABASE rdmp OWNER rdmp;
GRANT CONNECT ON DATABASE smi to rdmp;
EOF

./rdmp -- -f /dev/stdin --dir yaml <<EOF
Commands:
- CreateNewExternalDatabaseServer LiveLoggingServer_ID "DatabaseType:PostgreSql:Server=localhost;Uid=rdmp;Database=rdmp"
- ImportTableInfo "Table:IO_StudyTable:Schema:dicom:DatabaseType:PostgreSql:Server=localhost;Uid=rdmp;Database=smi" True
EOF
```

**Expected behavior**

The TableInfo is imported successfully.

**Screenshots**

N/A.

**RDMP Version**

v8.2.0

**Error with Stack Trace**

```console
...
Success:Tables created
Success:Setup Completed successfully
Success:There are no patches to apply so skipping patching
2024-07-09 13:40:55.6502 INFO Command Completed .
2024-07-09 13:40:55.7393 TRACE Running Command 'ExecuteCommandImportTableInfo' .
2024-07-09 13:40:55.7705 ERROR Error executing script.  Problem line was 'ImportTableInfo "Table:IO_StudyTable:Schema:dicom:DatabaseType:PostgreSql:Server=localhost;Uid=rdmp;Pwd=myPassword1.;Database=smi" True':Could not find any columns in table IO_StudyTable .
2024-07-09 13:40:55.7705 INFO Fatal error occurred so returning -1 . System.Exception: Error executing script.  Problem line was 'ImportTableInfo "Table:IO_StudyTable:Schema:dicom:DatabaseType:PostgreSql:Server=localhost;Uid=rdmp;Pwd=myPassword1.;Database=smi" True':Could not find any columns in table IO_StudyTable
 ---> System.Exception: Could not find any columns in table IO_StudyTable
   at FAnsi.Implementations.PostgreSql.PostgreSqlTableHelper.DiscoverColumns(DiscoveredTable discoveredTable, IManagedConnection connection, String database)
   at FAnsi.Discovery.DiscoveredTable.DiscoverColumns(IManagedTransaction managedTransaction)
   at Rdmp.Core.Curation.TableInfoImporter.DoImport(ITableInfo& tableInfoCreated, ColumnInfo[]& columnInfosCreated) in D:\a\RDMP\RDMP\Rdmp.Core\Curation\TableInfoImporter.cs:line 137
   at Rdmp.Core.CommandExecution.AtomicCommands.ExecuteCommandImportTableInfo.Execute() in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\AtomicCommands\ExecuteCommandImportTableInfo.cs:line 57
   at Rdmp.Core.CommandExecution.CommandInvoker.ExecuteCommand(ConstructorInfo constructorInfo, CommandLineObjectPicker picker) in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\CommandInvoker.cs:line 298
   at Rdmp.Core.CommandLine.Runners.ExecuteCommandRunner.RunCommand(String command) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\Runners\ExecuteCommandRunner.cs:line 104
   at Rdmp.Core.CommandLine.Runners.ExecuteCommandRunner.RunScript(RdmpScript script, IRDMPPlatformRepositoryServiceLocator repositoryLocator) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\Runners\ExecuteCommandRunner.cs:line 199
   --- End of inner exception stack trace ---
   at Rdmp.Core.CommandLine.Runners.ExecuteCommandRunner.RunScript(RdmpScript script, IRDMPPlatformRepositoryServiceLocator repositoryLocator) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\Runners\ExecuteCommandRunner.cs:line 204
   at Rdmp.Core.CommandLine.Runners.ExecuteCommandRunner.Run(IRDMPPlatformRepositoryServiceLocator repositoryLocator, IDataLoadEventListener listener, ICheckNotifier checkNotifier, GracefulCancellationToken token) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\Runners\ExecuteCommandRunner.cs:line 90
   at Rdmp.Core.CommandLine.RdmpCommandLineBootStrapper.Run(RDMPCommandLineOptions opts, IRunner explicitRunner, IRDMPPlatformRepositoryServiceLocator existingLocator) in D:\a\RDMP\RDMP\Rdmp.Core\CommandLine\RdmpCommandLineBootStrapper.cs:line 145                                    at Rdmp.Core.Program.HandleArguments(String[] args, Logger logger) in D:\a\RDMP\RDMP\Tools\rdmp\Program.cs:line 83
```

**Database Engine**

Postgres.

**Additional context**

N/A.

**Comment by rkm** [comment]
The bug may lie in FAnsi, actually

**Comment by rkm** [comment]
My mistake! This didn't work as the rdmp user needs a few more privileges:

```console
GRANT CONNECT ON DATABASE smi to rdmp;
GRANT USAGE ON SCHEMA dicom to rdmp;
GRANT SELECT ON ALL TABLES IN SCHEMA dicom to rdmp;
```

The error messaging could be improved here though, as it's not really clear that this was a permissions issue.

**Comment by JFriel** [comment]
Glad it's resolved. Will log an internal ticket to improve the error messaging
