### ISSUE TITLE
[8.2.0] LoadFiles DLE crashes with mixed Linux/Windows path

### ISSUE THREAD

**Issue by rkm** [HicServices/RDMP#1881]
**Describe the bug**

Running an existing DLE from the RDMP CLI after upgrading to v8.2.0 crashes with ` LoadFiles crashed while running Job  . System.IO.DirectoryNotFoundException: Could not find a part of the path '/path/to/load/\Data\ForLoading\'.`

**To Reproduce**
1. Have an existing DLE load definition on a pre-8.2.0 version (we had v8.0.6)
2. Upgrade to v8.2.0 and run patches
3. Run the DLE

**Expected behavior**

The DLE should function as it did before the update.

**Screenshots**

N/A.

**RDMP Version**

v8.2.0

**Error with Stack Trace**

```console
> ./rdmp dle --command run --LoadMetadata 12
2024-07-15 08:59:30.5465 INFO Dotnet Version:8.0.6 . 
2024-07-15 08:59:30.6049 INFO RDMP Version:8.2.0.0 . 
2024-07-15 08:59:39.0149 INFO Performing pre-execution checks . 
2024-07-15 08:59:39.9719 INFO Starting load for Loading CHI-EUPI mapping . 
2024-07-15 08:59:41.2170 ERROR LoadFiles crashed while running Job  . System.IO.DirectoryNotFoundException: Could not find a part of the path '/path/to/load/\Data\ForLoading\'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Rdmp.Core.DataLoad.Engine.LoadExecution.Components.LoadFiles.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in D:\a\RDMP\RDMP\Rdmp.Core\DataLoad\Engine\LoadExecution\Components\LoadFiles.cs:line 43
   at Rdmp.Core.DataLoad.Engine.LoadExecution.SingleJobExecution.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in D:\a\RDMP\RDMP\Rdmp.Core\DataLoad\Engine\LoadExecution\SingleJobExecution.cs:line 53
2024-07-15 08:59:41.2242 ERROR Job crashed . System.IO.DirectoryNotFoundException: Could not find a part of the path '/path/to/load/drop_in/\Data\ForLoading\'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Rdmp.Core.DataLoad.Engine.LoadExecution.Components.LoadFiles.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in D:\a\RDMP\RDMP\Rdmp.Core\DataLoad\Engine\LoadExecution\Components\LoadFiles.cs:line 43
   at Rdmp.Core.DataLoad.Engine.LoadExecution.SingleJobExecution.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in D:\a\RDMP\RDMP\Rdmp.Core\DataLoad\Engine\LoadExecution\SingleJobExecution.cs:line 53
2024-07-15 08:59:41.2260 INFO Disposing disposables... . 
2024-07-15 08:59:41.2345 INFO Exiting with code 1 . 
```

**Database Engine**

SQLServer

**Additional context**

N/A

**Comment by JFriel** [comment]
There is an update in v8.2.0 that takes the historical rood directory (locationOfFlatFiles )for the LoadMetadata and splits it into 4 new column (LocationOfForLoadingDirectory, LocationOfForArchivingDirectory , LocationOfExecutablesDirectory, LocationOfCacheDirectory) but the SQL patch was assuming windows file paths. You can manually modify those columns to fix the issue (replace the \ with / ), but I will look at a way to automatically handle this in v8.2.1

**Comment by rkm** [comment]
Thanks - manually updating the paths seems to have done the job!

Note that `check` didn't report any errors before, so perhaps it could be modified to check the existence of the load directories?

**Comment by JFriel** [comment]
Good idea, thanks! Will add it to the internal ticket
