### ISSUE TITLE
Plugin warnings with v8.2.1 CLI

### ISSUE THREAD

**Issue by rkm** [HicServices/RDMP#1898]
**Describe the bug**

When launching the CLI, the following messages are logged, but the program appears to function normally:

```console
> ./rdmp --dir ../x
2024-07-23 17:26:50.3221 INFO Dotnet Version:8.0.7 .
2024-07-23 17:26:50.3221 INFO RDMP Version:8.2.1.0 .
Could not load plugin component p/main/fr-FR/Terminal.Gui.resources.dll due to Assembly with same name is already loaded
Could not load plugin component p/main/ja-JP/Terminal.Gui.resources.dll due to Assembly with same name is already loaded
Could not load plugin component p/main/pt-PT/Terminal.Gui.resources.dll due to Assembly with same name is already loaded
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ReadYaml' in type 'DicomTypeTranslation.TableCreation.SystemTypeTypeConverter' from assembly 'DicomTypeTranslation, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Rdmp.Core.Repositories.MEF.PopulateUnique() in D:\a\RDMP\RDMP\Rdmp.Core\Repositories\MEF.cs:line 57
System.TypeLoadException: Method 'ReadYaml' in type 'DicomTypeTranslation.TableCreation.SystemTypeTypeConverter' from assembly 'DicomTypeTranslation, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ReadYaml' in type 'DicomTypeTranslation.TableCreation.SystemTypeTypeConverter' from assembly 'DicomTypeTranslation, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Rdmp.Core.Repositories.MEF.PopulateUnique() in D:\a\RDMP\RDMP\Rdmp.Core\Repositories\MEF.cs:line 57
System.TypeLoadException: Method 'ReadYaml' in type 'DicomTypeTranslation.TableCreation.SystemTypeTypeConverter' from assembly 'DicomTypeTranslation, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Enter Command (or Ctrl+C)
```

**To Reproduce**
1. Download rdmp-8.2.1-cli-linux-x64.tar.xz
2. Extract and run the program as above

**Expected behavior**

No warnings or exceptions.

**Screenshots**

N/A.

**RDMP Version**

v8.2.1

**Error with Stack Trace**

(See above)

**Database Engine**

N/A

**Additional context**

N/A

**Comment by jas88** [comment]
The first 3 are harmless but should have been prevented by `plugin pack`; I think the two `ReflectionTypeLoadException` instances are from using different incompatible versions of YamlDotNet, and a newer release of RdmpDicom should resolve that.
