### ISSUE TITLE
Extraction to Database pipeline warning Object reference not set instance

### ISSUE THREAD

**Issue by zzszarka** [HicServices/RDMP#199]
**Describe the bug**
On Extracting to Database, a warning:

Progress Message

Failed to get HashOnDataRelease columns for catalogue SMR00 - Outpatient Appointments with the exception: Object reference not set to an instance of an object. Columns can be ignored manually using the Ignore Columns option

**To Reproduce**
1. Run extraction to database

**Expected behavior**
1. Not completely sure what the software is trying to do.

**Screenshots**

**RDMP Version**
v4.2.0

**Error with Stack Trace**
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at ReusableLibraryCode.Progress.NotifyEventArgs..ctor(ProgressEventType progressEventType, String message) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Reusable\ReusableLibraryCode\Progress\NotifyEventArgs.cs:line 32
   at HICPluginInteractive.DataFlowComponents.CHIColumnFinder.PreInitialize(IExtractCommand value, IDataLoadEventListener listener)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Rdmp.Core.DataFlowPipeline.Requirements.DataFlowPipelineContext`1.PreInitializeComponentWithSingleObject(IDataLoadEventListener listener, Object component, Object value, Dictionary`2 initializedComponents) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataFlowPipeline\Requirements\DataFlowPipelineContext.cs:line 295
   at Rdmp.Core.DataFlowPipeline.Requirements.DataFlowPipelineContext`1.PreInitializeComponentWithAllObjects(IDataLoadEventListener listener, Object component, Object[] parameters) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataFlowPipeline\Requirements\DataFlowPipelineContext.cs:line 247
   at Rdmp.Core.DataFlowPipeline.DataFlowPipelineEngine`1.Initialize(Object[] initializationObjects) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataFlowPipeline\DataFlowPipelineEngine.cs:line 88
   at Rdmp.Core.Curation.Data.Pipelines.PipelineUseCase.GetEngine(IPipeline pipeline, IDataLoadEventListener listener) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\Curation\Data\Pipelines\PipelineUseCase.cs:line 103
   at Rdmp.Core.DataExport.DataExtraction.Pipeline.ExtractionPipelineUseCase.GetEngine(IPipeline pipeline, IDataLoadEventListener listener) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataExport\DataExtraction\Pipeline\ExtractionPipelineUseCase.cs:line 162
   at Rdmp.Core.DataExport.DataExtraction.Pipeline.ExtractionPipelineUseCase.Execute(IDataLoadEventListener listener) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataExport\DataExtraction\Pipeline\ExtractionPipelineUseCase.cs:line 81
   at Rdmp.Core.CommandLine.Runners.ExtractionRunner.ExecuteRun(Object runnable, OverrideSenderIDataLoadEventListener listener) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\CommandLine\Runners\ExtractionRunner.cs:line 120
   at Rdmp.Core.CommandLine.Runners.ManyRunner.<>c__DisplayClass12_1.<Run>b__0() in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\CommandLine\Runners\ManyRunner.cs:line 70
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by tznind** [comment]
This looks like an issue with CHIColumnFinder in the HIC plugin not the main RDMP codebase

**Comment by tznind** [comment]
This behaviour has been fixed in the plugin
