### ISSUE TITLE
System.Windows.Forms.DataVisualization wants System.Data.SqlClient not Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#471]
```csharp
Error

Could not load file or assembly 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

   at System.Windows.Forms.DataVisualization.Charting.ChartImage.DataBind()
   at System.Windows.Forms.DataVisualization.Charting.ChartPicture.Paint(Graphics graph, Boolean paintTopLevelElementOnly)
   at System.Windows.Forms.DataVisualization.Charting.Chart.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by tznind** [comment]
We could fix this by:

- Adding a dependency on System.Data.SqlClient into the main RDMP binary (ugh)
- Forking https://github.com/dotnet/winforms-datavisualization and updating it to use Microsoft.Data.SqlClient and releasing a nuget package
- Porting our charting code to use a different graph/charting package

**Comment by tznind** [comment]
I have had a look at forking and have got it building in dotnet 5 with Microsoft.Data.SqlClient. 

See: https://github.com/HicServices/winforms-datavisualization/issues/1
