### ISSUE TITLE
SFTP Downloader Error on rdmp rl

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#685]
One of the dataloads failed twice in a row on rdmp_rl
1: 23/03/2021 17:31
2: 30/03/2021 17:27

Error Log:
SingleJobExecution (30/03/2021 17:27:08)
The connection was closed by the server: Manually close SSH session. (ByApplication).
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
   at Rdmp.Core.DataLoad.Modules.FTP.SFTPDownloader.Download(String file, ILoadDirectory destination, IDataLoadEventListener job) in Z:\Repos\RDMP\Rdmp.Core\DataLoad\Modules\FTP\SFTPDownloader.cs:line 36
   at Rdmp.Core.DataLoad.Modules.FTP.FTPDownloader.DownloadFilesOnFTP(ILoadDirectory destination, IDataLoadEventListener listener) in Z:\Repos\RDMP\Rdmp.Core\DataLoad\Modules\FTP\FTPDownloader.cs:line 117
   at Rdmp.Core.DataLoad.Modules.FTP.FTPDownloader.Fetch(IDataLoadJob job, GracefulCancellationToken cancellationToken) in Z:\Repos\RDMP\Rdmp.Core\DataLoad\Modules\FTP\FTPDownloader.cs:line 72
   at Rdmp.Core.DataLoad.Engine.LoadExecution.Components.Runtime.DataProviderRuntimeTask.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in Z:\Repos\RDMP\Rdmp.Core\DataLoad\Engine\LoadExecution\Components\Runtime\DataProviderRuntimeTask.cs:line 56
   at Rdmp.Core.DataLoad.Engine.LoadExecution.Components.CompositeDataLoadComponent.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in Z:\Repos\RDMP\Rdmp.Core\DataLoad\Engine\LoadExecution\Components\CompositeDataLoadComponent.cs:line 33
   at Rdmp.Core.DataLoad.Engine.LoadExecution.Components.LoadFiles.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in Z:\Repos\RDMP\Rdmp.Core\DataLoad\Engine\LoadExecution\Components\LoadFiles.cs:line 41
   at Rdmp.Core.DataLoad.Engine.LoadExecution.SingleJobExecution.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in Z:\Repos\RDMP\Rdmp.Core\DataLoad\Engine\LoadExecution\SingleJobExecution.cs:line 52

**Comment by RoyMudie** [comment]
Roy Mudie added a comment - 03/Nov/21 3:42 PM
Error was when process was automated chi load with jenkins.

[~zzszarka] to test with [~chall] if this has been resolved with with "keep alive" setting being enabled.
