### ISSUE TITLE
Error creating Catalogue 'item with same key already added' [Zsolt]

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#763]
While configuring a catalogues etractability:
![image](https://user-images.githubusercontent.com/5470814/144584494-5b952617-2ea2-4aff-af50-0489ad83bdd6.png)

```
An item with the same key has already been added. Key: 67698
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rdmp.Core.Providers.CatalogueChildProvider..ctor(ICatalogueRepository repository, IChildProvider[] pluginChildProviders, ICheckNotifier errorsCheckNotifier, CatalogueChildProvider previousStateIfKnown) in D:\a\RDMP\RDMP\Rdmp.Core\Providers\CatalogueChildProvider.cs:line 311
   at Rdmp.Core.Providers.DataExportChildProvider..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, IChildProvider[] pluginChildProviders, ICheckNotifier errorsCheckNotifier, DataExportChildProvider previousStateIfKnown) in D:\a\RDMP\RDMP\Rdmp.Core\Providers\DataExportChildProvider.cs:line 99
   at Rdmp.Core.CommandExecution.BasicActivateItems.GetChildProvider() in D:\a\RDMP\RDMP\Rdmp.Core\CommandExecution\BasicActivateItems.cs:line 124
```

**Comment by RoyMudie** [comment]
This appears to be a similar/same issue reported by Scott while saving a Load Progress variable (which can be found under Load Configurations -> Data Loads -> Select Data Load -> Scheduling
![image](https://user-images.githubusercontent.com/5470814/144830055-14587566-1f65-4414-b854-81963ca87e44.png)


`
An item with the same key has already been added. Key: 67698
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rdmp.Core.Providers.CatalogueChildProvider..ctor(ICatalogueRepository repository, IChildProvider[] pluginChildProviders, ICheckNotifier errorsCheckNotifier, CatalogueChildProvider previousStateIfKnown) in D:\a\RDMP\RDMP\Rdmp.Core\Providers\CatalogueChildProvider.cs:line 311
   at Rdmp.Core.Providers.DataExportChildProvider..ctor(IRDMPPlatformRepositoryServiceLocator repositoryLocator, IChildProvider[] pluginChildProviders, ICheckNotifier errorsCheckNotifier, DataExportChildProvider previousStateIfKnown) in D:\a\RDMP\RDMP\Rdmp.Core\Providers\DataExportChildProvider.cs:line 99
`

**Comment by tznind** [comment]
Ok I think that there are 2 `ExtractionInformation` objects in the RDMP `CatalogueChildProvder` that have the same `CatalogueItem_ID`.  

There is a database constraint that prevents this from happening so it must be a stale cache (something to do with `RowVerCache`).

Presumably something like

1. Person A makes CatalogueItem 2 extractable and defines SQL
2. Everyone gets the info of the new object (ExtractionInformation)
3. ExtractionInformation is deleted and a new one created 
4. `RowVerCache` is not detecting the delete and so picks up the new one and keeps the stale one.
5. `CatalogueChildProvder` fails to build a definitive 1-1 mapping between ExtractionInformation and CatalogueItem
